### ISSUE TITLE
Wrong credentials ERROR

### ISSUE THREAD

**Issue by wesleyhf** [firework/sparklez#37]
If you connect and change the tab, the credentials of the first tab is lost.

**Comment by Jfeng3** [comment]
@dbpolito  @wesleyhf  what is the solution for connect ETIMEOUT error here? 
I am running on aws ec2 ubuntu

**Comment by dbpolito** [comment]
@Jfeng3 This issue is on a really old version, which probably isn't related.

Are you able to connect using MySQL from your machine? Usually MySQL servers are closed to outside and you need SSH Tunnel, which isn't currently supported.
